services:
  frontend:
    build: .
    container_name: frontend
    restart: "unless-stopped"
    environment:
      - VITE_APP_BACKEND_URL=https://vv.shamps.dev/api
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.entrypoints=https
      - traefik.http.routers.frontend.rule=Host(`vv.shamps.dev`)
      - traefik.http.routers.frontend.tls.certresolver=letsEncrypt
      - traefik.http.services.frontend.loadbalancer.server.port=80
    networks:
      - traefik
  
networks:
  traefik:
    name: traefik
    external: true
